// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqP1pIpypew_ITPQ4FdbyZ2SnupFNxdU',
    appId: '1:1012816850975:android:4ab1eba9ac70018510252a',
    messagingSenderId: '1012816850975',
    projectId: 'hazrat-first-flutter-app',
    storageBucket: 'hazrat-first-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Of6fPRLaqApD02QO3eA50Kr9yxTqIWo',
    appId: '1:1012816850975:ios:332a7013ca2187ec10252a',
    messagingSenderId: '1012816850975',
    projectId: 'hazrat-first-flutter-app',
    storageBucket: 'hazrat-first-flutter-app.appspot.com',
    iosClientId: '1012816850975-q7vib2s95u7c078ntqh5751588j83su4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstflutterapp.firstFlutterApp',
  );
}
